name: node-api
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: sagarvs/node-api
        ports:
          - 3000:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3000/api/user -H ''Content-Type: application/json'' -d ''{\"username\": \"hello\",\"address\": \"dwded\"}'''
      - name: Get Users
        run: curl http://localhost:3000/api/users
    